import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {signup,survey,withdraw,jstDay} from '../server/intake.mjs';
function database(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON;');sql.exec(readFileSync(new URL('../drizzle/0000_curly_slapstick.sql',import.meta.url),'utf8'));const db={prepare(query){return {bind(...values){return {first:async()=>sql.prepare(query).get(...values),run:async()=>sql.prepare(query).run(...values),query,values}}}},async batch(statements){sql.exec('BEGIN');try{for(const s of statements)sql.prepare(s.query).run(...s.values);sql.exec('COMMIT')}catch(e){sql.exec('ROLLBACK');throw e}}};return {db,sql}}
const identity={id:'550e8400-e29b-41d4-a716-446655440000',key:'a'.repeat(64)};
const input={...identity,store:'テスト店',business:'カフェ',area:'大通周辺',email:'Test@example.com',consent:true,website:''};
const answer={...identity,uses:3,minutes:20,useful:'地域・期間の絞り込み',willingness:'継続したい',feedback:'助かった',consent:true};
function request(data,origin='https://trial.example'){return new Request('https://trial.example/api/test',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(data)})}
const now=new Date('2026-10-04T16:00:00Z');
test('JSTで14日間・500円、再送で申込が増えず個人情報を返さない',async()=>{const {db,sql}=database();const r=await signup(request(input),db,now);assert.equal(r.status,201);const body=await r.json();assert.equal(body.start_date,'2026-10-05');assert.equal(body.end_date,'2026-10-18');assert.equal(body.price_yen,500);assert.equal(body.email,undefined);assert.equal(body.key_hash,undefined);assert.equal((await signup(request(input),db,now)).status,201);assert.equal(sql.prepare('SELECT COUNT(*) n FROM trials').get().n,1);const row=sql.prepare('SELECT * FROM trials').get();assert.equal(row.email,'test@example.com');assert.notEqual(row.key_hash,identity.key);assert.equal(row.key_hash.length,64)});
test('同じIDでも違う鍵は拒否し店舗情報を変えない',async()=>{const {db,sql}=database();await signup(request(input),db,now);assert.equal((await signup(request({...input,key:'b'.repeat(64),store:'他店'}),db,now)).status,403);assert.equal(sql.prepare('SELECT store FROM trials').get().store,'テスト店')});
test('入力・同意・形式・別サイト送信・長さを検証',async()=>{const {db}=database();for(const change of [{email:'invalid'},{store:''},{business:'invalid'},{consent:false},{id:'invalid'},{website:'spam'}])assert.equal((await signup(request({...input,...change}),db,now)).status,400);assert.equal((await signup(request(input,'https://other.example'),db,now)).status,403);assert.equal((await signup(request({...input,extra:'x'.repeat(17000)}),db,now)).status,413);assert.equal((await signup(new Request('https://trial.example/api/test',{method:'POST',headers:{origin:'https://trial.example','content-type':'application/json'},body:'{'}),db,now)).status,400)});
test('回答は本人のみ・修正は1件のまま・価格はサーバーで固定',async()=>{const {db,sql}=database();assert.equal((await survey(request(answer),db,now)).status,403);await signup(request(input),db,now);assert.equal((await survey(request({...answer,key:'b'.repeat(64)}),db,now)).status,403);assert.equal((await survey(request({...answer,price_yen:1}),db,now)).status,200);assert.equal((await survey(request({...answer,uses:4}),db,now)).status,200);const row=sql.prepare('SELECT * FROM answers').get();assert.equal(row.price_yen,500);assert.equal(row.uses,4);assert.equal(sql.prepare('SELECT COUNT(*) n FROM answers').get().n,1);for(const change of [{uses:-1},{minutes:10081},{uses:1.5},{consent:false},{feedback:'x'.repeat(2001)}])assert.equal((await survey(request({...answer,...change}),db,now)).status,400)});
test('本人の確認後のみ申込と回答を削除',async()=>{const {db,sql}=database();await signup(request(input),db,now);await survey(request(answer),db,now);assert.equal((await withdraw(request({...identity,confirm:false}),db)).status,400);assert.equal((await withdraw(request({...identity,key:'b'.repeat(64),confirm:true}),db)).status,403);assert.equal((await withdraw(request({...identity,confirm:true}),db)).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM answers').get().n,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM trials').get().n,0);assert.equal((await survey(request(answer),db,now)).status,403)});
test('接続できない場合に保存成功を返さない',async()=>{for(const handler of [signup,survey,withdraw])assert.equal((await handler(request(input),null)).status,503);assert.equal(jstDay(new Date('2026-10-04T14:59:59Z')),'2026-10-04');assert.equal(jstDay(new Date('2026-10-04T15:00:00Z')),'2026-10-05')});
