'use client';
import {useEffect,useState} from 'react';
import {USEFUL,WILLINGNESS} from '@/server/intake.mjs';
type Identity={id:string;key:string};
function readLink(value:string):Identity|null{try{const p=new URLSearchParams(new URL(value,location.origin).hash.slice(1));const id=p.get('id'),key=p.get('key');return id&&key?{id,key}:null}catch{return null}}
export default function SurveyForm(){
 const [identity,setIdentity]=useState<Identity|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[linkValue,setLinkValue]=useState(''),[withdrawn,setWithdrawn]=useState(false);
 useEffect(()=>{const fromLink=readLink(location.href);if(fromLink){setIdentity(fromLink);return}try{const saved=JSON.parse(localStorage.getItem('pro-trial-registration')||'null');if(saved?.id&&saved?.key)setIdentity({id:saved.id,key:saved.key})}catch{}},[]);
 async function post(path:string,payload:Record<string,unknown>){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,...identity}),signal:controller.signal});const result=await r.json() as {ok:boolean;error?:string;trial_number?:string};if(!r.ok||!result.ok)throw new Error(result.error||'保存できませんでした。');return result}finally{clearTimeout(timeout)}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');const fields=Object.fromEntries(new FormData(e.currentTarget));try{const r=await post('/api/survey',{...fields,uses:Number(fields.uses),minutes:Number(fields.minutes),consent:fields.consent==='on'});setMessage(`回答を運営側に保存しました（${r.trial_number}）。ありがとうございました。修正する場合はこの画面から再送信できます。`)}catch(e){setError(e instanceof Error&&e.name!=='AbortError'?e.message:'保存結果を確認できませんでした。同じ画面から再送信してください。')}finally{setBusy(false)}}
 async function withdraw(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await post('/api/withdraw',{confirm:true});setWithdrawn(true);try{localStorage.removeItem('pro-trial-registration')}catch{}}catch(e){setError(e instanceof Error?e.message:'取り消しができませんでした。')}finally{setBusy(false)}}
 if(withdrawn)return <div className="success" role="status"><h2>申し込みを取り消しました</h2><p>店舗・連絡先・アンケートの保存内容を削除しました。</p><a href="/">受付ページへ戻る</a></div>;
 if(!identity)return <section className="panel"><p>申し込み後に表示された専用の回答リンクを開いてください。同じブラウザなら保存済みの申し込みから回答できます。</p><label>保存した回答リンク<input type="url" value={linkValue} onChange={e=>setLinkValue(e.target.value)} placeholder="https://…/survey#id=…"/></label><div className="actions"><button type="button" onClick={()=>{const who=readLink(linkValue);if(who){setIdentity(who);setError('')}else setError('回答リンクを確認してください。')}}>回答を開く</button><a href="/">無料試用を申し込む</a></div><p className="error" role="status">{error}</p></section>;
 return <><section className="panel"><p className="small muted">受付番号：P-{identity.id.slice(0,8).toUpperCase()} ／ 月額500円（税込・想定）</p><form onSubmit={submit}><div className="grid"><label>1週間に使った回数<input name="uses" type="number" min={0} max={100} required/></label><label>週に短縮できた調査時間（分）<input name="minutes" type="number" min={0} max={10080} required/></label><label>最も役立った機能<select name="useful" required defaultValue=""><option value="" disabled>選んでください</option>{USEFUL.map(v=><option key={v}>{v}</option>)}</select></label><label>月額500円での継続<select name="willingness" required defaultValue=""><option value="" disabled>選んでください</option>{WILLINGNESS.map(v=><option key={v}>{v}</option>)}</select></label><label className="wide">実際に変えた営業判断・改善してほしい点<textarea name="feedback" maxLength={2000} placeholder="仕込み・配置・告知など。個人情報は入力しないでください。"/></label></div><label className="check"><input name="consent" type="checkbox" required/><span>回答を試用の検証・改善に利用することを確認しました。<a href="/privacy">入力情報の取り扱い</a></span></label><button disabled={busy}>{busy?'保存しています…':'アンケートを送信する'}</button><p className="status" role="status">{message}</p><p className="status error" role="status">{error}</p></form></section><details className="panel"><summary>申し込みを取り消して保存内容を削除する</summary><p className="small muted">店舗情報・メール・アンケートを削除し、この回答リンクは使えなくなります。</p><form onSubmit={withdraw}><label className="check"><input type="checkbox" required/>保存内容を削除することを確認しました。</label><button className="secondary" disabled={busy}>取り消して削除する</button></form></details></>
}
